spring:
    profiles:
    active: dev
--  
#生产环境
spring:
    profiles: dev
    applicaion: 
        name: microservicecloud-config-zzy-dev
--   
spring:
    profiles: test
    applicaion: 
        name: microservicecloud-config-zzy-test